info:
  app:
    name: dewey-service
    description: Microservice for Dewey

server:
  port: 8022

spring:
  dewey:
    deweyListPath: /dewey-list.xml

---

spring:
  profiles: test

  dewey:
    deweyListPath: /dewey-list-TEST.xml